// packages/vue/core/components/avatar.vue
<script setup lang="ts">
import type { AvatarProps } from '@blank/types'
import { computed } from 'vue'

const props = withDefaults(defineProps<AvatarProps>(), {
    size: 'medium',
    rounded: 'none',
    src: '',
    name: '',
})

const initials = computed(() => {
    if (!props.name)
        return ''
    return props.name
        .split(' ')
        .map(word => word.charAt(0).toUpperCase())
        .join('')
        .slice(0, 2)
})
</script>

<template>
    <div :class="`blank__avatar ${props.size} ${props.rounded ? 'rounded' : ''}`">
        <img v-if="props.src" :src="props.src" :alt="props.name" class="src">
        <span v-else-if="initials">{{ initials }}</span>
        <img v-else alt="default avatar" class="src">
    </div>
</template>

// packages/react/core/components/avatar.tsx
import type { AvatarProps } from '@blank/types'
import type { PropsWithChildren } from 'react'

function Avatar({ size = 'medium', name, src, rounded = 'none' }: PropsWithChildren<AvatarProps>) {
    const initials = name
        ? name
            .split(' ')
            .map(word => word.charAt(0).toUpperCase())
            .join('')
            .slice(0, 2)
        : ''
    return (
        <div className={`blank__avatar ${size} ${rounded}`}>
            {src
                ? (
                        <img src={src} alt={name} className="src" />
                    )
                : initials
                    ? (
                            <span>{initials}</span>
                        )
                    : (
                            <img src="" alt="default avatar" className="src" />
                        )}
        </div>
    )
}

export default Avatar
