// packages/vue/core/components/button.vue
<script setup lang="ts">
import type { ButtonProps } from '@blank/types'
import { computed } from 'vue'

const props = withDefaults(defineProps<ButtonProps>(), {
	variant: 'primary',
	size: 'medium',
	appearance: 'default',
	disabled: false,
})

const classes = computed(() => {
	return {
		[props.appearance]: true,
		[props.variant]: true,
		[props.size]: true,
	}
})
</script>

<template>
	<button class="blank__button" :class="classes" :disabled="disabled">
		<slot />
	</button>
</template>

// packages/react/core/components/button.tsx
import type { ButtonProps } from '@blank/types'
import type { PropsWithChildren } from 'react'

function Button({ variant = 'primary', size = 'medium', disabled, children }: PropsWithChildren<ButtonProps>) {
    return (
        <button className={`blank__button ${variant} ${size} ${disabled ? 'disabled' : ''}`} disabled={disabled}>
            {children}
        </button>
    )
}

export default Button
