// packages/vue/core/components/buttonGroup.vue
<script setup lang="ts">
import type { ButtonGroupProps } from '@blank/types'
import { provide } from 'vue'

const props = withDefaults(defineProps<ButtonGroupProps>(), {
    size: 'medium',
})

provide('buttonGroup', {
    size: props.size,
})
</script>

<template>
    <div
        class="blank__button-group"
        role="group"
        aria-labelledby="button-group-label"
    >
        <slot />
    </div>
</template>

// packages/react/core/components/buttonGroup.tsx
import type { ButtonGroupProps } from '@blank/types'
import type { PropsWithChildren } from 'react'
import React, { createContext, useContext } from 'react'

const ButtonGroupContext = createContext<{ size: 'small' | 'medium' | 'large' }>({ size: 'medium' })

const ButtonGroup: React.FC<PropsWithChildren<ButtonGroupProps>> = ({ size = 'medium', children }) => {
    return (
        <ButtonGroupContext.Provider value={{ size }}>
            <div
                className="blank__button-group"
                role="group"
                aria-label="Button group"
            >
                {children}
            </div>
        </ButtonGroupContext.Provider>
    )
}

export function useButtonGroup() {
    return useContext(ButtonGroupContext)
}

export default ButtonGroup
