// packages/vue/core/components/checkbox.vue
<script setup lang="ts">
import type { CheckboxProps } from '@blank/types'
import { ref, watch } from 'vue'

const props = withDefaults(defineProps<CheckboxProps>(), {
    size: 'medium',
    direction: 'left',
    label: '',
    checked: false,
    disabled: false,
})

const internalChecked = ref(props.checked)

watch(() => props.checked, (newChecked) => {
    internalChecked.value = newChecked
})

function handleClick() {
    if (props.disabled)
        return

    internalChecked.value = !internalChecked.value

    if (props.onChange) {
        props.onChange(internalChecked.value)
    }
}
</script>

<template>
    <div
        class="blank checkbox"
        :class="[props.size, props.direction, { disabled: props.disabled }] "
        tabindex="0"
        role="checkbox"
        :aria-checked="internalChecked"
        :aria-disabled="props.disabled"
        @click="handleClick"
    >
        <input
            v-model="internalChecked"
            type="checkbox"
            class="blank checkbox__input"
            :class="props.size"
            :aria-label="props.label"
            :disabled="props.disabled"
        >
        <span
            class="blank checkbox__label"
            :class="[props.size, { disabled: props.disabled }] "
        >
            {{ props.label }}
        </span>
    </div>
</template>

// packages/react/core/components/checkbox.tsx
import type { CheckboxProps } from '@blank/types'
import React from 'react'

const Checkbox: React.FC<CheckboxProps> = ({
    size = 'medium',
    direction,
    label,
    checked,
    onChange,
    disabled = false,
}) => {
    const handleClick = () => {
        if (disabled)
            return
        if (onChange) {
            onChange(!checked)
        }
    }

    return (
        <div
            className={`blank checkbox ${size} ${direction} ${disabled ? 'disabled' : ''}`}
            onClick={handleClick}
            tabIndex={disabled ? -1 : 0}
            role="checkbox"
            aria-checked={checked}
            aria-disabled={disabled}
        >
            <input
                type="checkbox"
                className={`blank checkbox__input ${size}`}
                checked={checked}
                onChange={e => e.stopPropagation()}
                aria-label={label}
                disabled={disabled}
            />
            <span className={`blank checkbox__label ${size} ${disabled ? 'disabled' : ''}`}>
                {label}
            </span>
        </div>
    )
}

export default Checkbox
