// packages/vue/core/components/toggle.vue
<script setup lang="ts">
import type { Toggle as ToggleType } from '@blank/types'
import { defineEmits, defineProps, ref, watch, withDefaults } from 'vue'

const props = withDefaults(defineProps<ToggleType.ToggleProps>(), {
	size: 'medium',
	label: '',
	labelDirection: 'left',
	disabled: false,
	checked: false,
	onChange: undefined,
})

const emit = defineEmits<{
	(e: 'onChange', value: boolean): void
}>()

const isActive = ref(!!props.checked)

watch(() => props.checked, (newVal) => {
	isActive.value = !!newVal
})

function handleToggle() {
	if (!props.disabled) {
		const newState = !isActive.value
		isActive.value = newState
		emit('onChange', newState)
	}
}
</script>

<template>
	<div :class="`blank__toggle-container ${labelDirection}`">
		<span v-if="label" :class="`toggle-label ${size} ${disabled ? 'disabled' : ''}`">
			{{ label }}
		</span>
		<div
			:aria-checked="isActive ? 'true' : 'false'"
			:aria-disabled="disabled"
			:class="`toggle ${size} ${isActive ? 'active' : ''} ${disabled ? 'disabled' : ''} toggle-position`"
			@click="handleToggle"
		>
			<span class="toggle-circle" />
		</div>
	</div>
</template>

// packages/react/core/components/toggle.tsx
import type { Toggle as ToggleType } from '@blank/types'
import type { PropsWithChildren } from 'react'
import React, { useEffect, useState } from 'react'

function Toggle({
	size = 'medium',
	checked,
	onChange,
	label,
	labelDirection,
	disabled = false,
}: PropsWithChildren<ToggleType.ToggleProps> & { onChange?: (newValue: boolean) => void }) {
	const [isActive, setIsActive] = useState<boolean>(!!checked)

	useEffect(() => {
		setIsActive(!!checked)
	}, [checked])

	const handleToggle = () => {
		if (!disabled) {
			const newState = !isActive
			setIsActive(newState)
			if (onChange) {
				onChange(newState)
			}
		}
	}

	return (
		<div className={`blank__toggle-container ${labelDirection}`}>
			{label && (
				<span className={`toggle-label ${size} ${disabled ? 'disabled' : ''}`}>
					{label}
				</span>
			)}
			<div
				onClick={!disabled ? handleToggle : undefined}
				aria-checked={isActive ? 'true' : 'false'}
				aria-disabled={disabled}
				className={`toggle ${size} ${isActive ? 'active' : ''} ${disabled ? 'disabled' : ''} toggle-position`}
			>
				<span className="toggle-circle" />
			</div>
		</div>
	)
}

export default Toggle
