// packages/react/core/components/badge.tsx
import type { BadgeProps } from '@blank/types'
import type { PropsWithChildren } from 'react'

function Badge({ size, variant, children, onClick }: PropsWithChildren<BadgeProps>) {
    return (
        <div
            onClick={onClick}
            className={`blank__badge ${variant} ${size} ${onClick !== undefined ? 'clickable' : ''}`}
            role={onClick ? 'button' : undefined}
            aria-label={onClick ? 'Click to perform action' : undefined}
            tabIndex={onClick ? 0 : undefined}
            aria-disabled={!onClick}
        >
            {children}
        </div>
    )
}

export default Badge

// packages/vue/core/components/badge.vue
<script setup lang="ts">
import type { BadgeProps } from '@blank/types'
import { defineProps, withDefaults } from 'vue'

const props = withDefaults(defineProps<BadgeProps>(), {
    size: 'small',
    variant: 'default',
    onClick: undefined,
})
</script>

<template>
    <div
        class="blank__badge"
        :class="[props.variant, props.size, { clickable: props.onClick }]"
        role="button"
        :aria-label="`Badge ${props.variant} ${props.size}`"
        :tabindex="props.onClick ? 0 : -1"
        :aria-disabled="!props.onClick"
        @click="props.onClick"
    >
        <slot />
    </div>
</template>
