// packages/react/core/components/input/base.tsx
import type { InputProps } from '@blank/types'
// Base.tsx
import React, { useMemo } from 'react'
import Icon from '../../common/icon'

interface BaseProps extends InputProps {
    className?: string
    tailSlot?: React.ReactNode
    leadSlot?: React.ReactNode
    value: string
    onChange?: (value: string) => void
}

const Base: React.FC<BaseProps> = ({
    id = 'input',
    type = 'text',
    size = 'medium',
    label,
    disabled,
    error,
    placeholder,
    tail,
    lead,
    tailSlot,
    leadSlot,
    value,
    onChange,
}) => {
    const classes = useMemo(() => ({
        disabled,
        error,
    }), [disabled, error])

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        onChange?.(e.target.value)
    }

    return (
        <div className={`blank__input ${Object.entries(classes)
            .filter(([_, value]) => value)
            .map(([key]) => key)
            .join(' ')}`}
        >
            <label className="blank__input__label" htmlFor={id}>
                {label}
            </label>
            <div className={`blank__input__base ${size}`}>
                {(tail || tailSlot) && (
                    <div className={`slot tail ${tail?.size || 'small'}`}>
                        {tailSlot || (tail?.name && <Icon name={tail.name} size={tail.size} />)}
                    </div>
                )}

                <input
                    id={id}
                    value={value}
                    onChange={handleChange}
                    aria-describedby={error ? 'hint' : undefined}
                    aria-invalid={error ? true : undefined}
                    type={type}
                    placeholder={placeholder}
                    className={`
            ${tail ? `tail__${tail?.size || 'small'}` : ''}
            ${lead ? `lead__${lead?.size || 'small'}` : ''}`.trim()}
                    disabled={disabled}
                />

                {(lead || leadSlot) && (
                    <div className={`slot lead ${lead?.size || 'small'}`}>
                        {leadSlot || (lead?.name && <Icon name={lead.name} size={lead.size} />)}
                    </div>
                )}
            </div>
        </div>
    )
}

export default Base

// packages/vue/core/components/input/base.vue
<script setup lang="ts">
import type { InputProps } from '@blank/types'
import { computed } from 'vue'
import Icon from '../../common/icon.vue'

const props = withDefaults(defineProps<InputProps>(), {
    id: 'input',
    type: 'text',
    size: 'medium',
})

const slots = defineSlots<{
    tail: Record<string, any>
    lead: Record<string, any>
    default?: (_: Record<string, any>) => any
}>()

const tail = computed(() => props.tail || slots.tail)
const lead = computed(() => props.lead || slots.lead)

const classes = computed(() => ({
    disabled: props.disabled,
    error: props.error,
}))
</script>

<template>
    <div class="blank__input" :class="classes">
        <label class="blank__input__label" :for="props.id">
            {{ label }}
        </label>
        <div class="blank__input__base" :class="props.size">
            <div v-if="tail || slots.tail" class="slot tail" :class="tail?.size || 'small'">
                <slot v-if="slots.tail" name="tail" />
                <Icon v-else-if="tail?.name" class="icon" :name="tail.name" :size="tail.size" />
            </div>

            <input
                :id="props.id"
                :aria-describedby="props.error ? 'hint' : undefined"
                :aria-invalid="props.error ? 'true' : undefined"
                :type="props.type"
                :placeholder="props.placeholder"
                :class="{
                    [`tail__${tail?.size || 'small'}`]: tail,
                    [`lead__${lead?.size || 'small'}`]: lead,
                }"
                :disabled="props.disabled"
            >

            <div v-if="lead || slots.lead" class="slot lead" :class="lead?.size || 'small'">
                <slot v-if="slots.lead" name="lead" />
                <Icon v-else-if="lead?.name" class="icon" :name="lead.name" :size="lead.size" />
            </div>
        </div>
    </div>
</template>
