// packages/react/core/components/input/url.tsx
import type { InputProps } from '@blank/types'

import React from 'react'
import Base from './base'

interface UrlProps extends InputProps {
    value: string
    className?: string
    onChange: (value: string) => void
}

const Url: React.FC<UrlProps> = (props) => {
    return (
        <Base
            {...props}
            tail={{ size: 'medium' }}
            tailSlot={(
                <div className="url-slot">
                    https://
                </div>
            )}
        />
    )
}

export default Url

// packages/vue/core/components/input/url.vue
<script setup lang="ts">
import type { InputProps } from '@blank/types'
import Base from './base.vue'

const props = defineProps<InputProps>()
</script>

<template>
    <Base v-bind="props" :tail="{ size: 'medium' }">
        <template #tail>
            <div class="url-slot">
                https://
            </div>
        </template>
    </Base>
</template>
