// packages/vue/core/components/input/index.vue
<script setup lang="ts">
import type { InputProps } from '@blank/types'
import { useSlots } from 'vue'

import base from './base.vue'
import creditCard from './creditCard.vue'
import currency from './currency.vue'
import phone from './phone.vue'
import url from './url.vue'

const { appearance = 'default', ...inputProps } = defineProps<InputProps>()

const appearanceMap = {
    'default': base,
    'phone': phone,
    'currency': currency,
    'crypto': undefined,
    'url': url,
    'credit-card': creditCard,
}

const slots = useSlots()
</script>

<template>
    <component :is="appearanceMap[appearance]" v-bind="inputProps" :class="appearance">
        <template v-for="(_, name) in slots" #[name]="slot">
            <slot :name="name" v-bind="slot" />
        </template>
    </component>
</template>

// packages/react/core/components/input/index.tsx
import type { InputProps } from '@blank/types'
import React from 'react'

import Base from './base'
import CreditCard from './creditCard'
import Currency from './currency'
import Phone from './phone'
import Url from './url'

type AppearanceType = 'default' | 'phone' | 'currency' | 'crypto' | 'url' | 'credit-card'

interface InputComponentProps extends InputProps {
    appearance?: AppearanceType
    children?: React.ReactNode
    value?: string
    onChange?: (value: string) => void
    className?: string
}

const appearanceMap = {
    'default': Base,
    'phone': Phone,
    'currency': Currency,
    'crypto': undefined,
    'url': Url,
    'credit-card': CreditCard,
} as const

const Input: React.FC<InputComponentProps> = ({
    appearance = 'default',
    children,

    ...inputProps
}) => {
    const Component = appearanceMap[appearance] || Base

    if (!Component) {
        return <Base {...inputProps} value={inputProps.value || ''} className={appearance} />
    }

    return (
        <Component {...inputProps} value={inputProps.value || ''} className={appearance || ''} onChange={inputProps.onChange || (() => {})} />
    )
}

export default Input
